#!/bin/bash

echo "Darakbang Engine: Database Configurator"
echo "Copyright (c) Team StarGarden"
echo

read -p "DB Host (default: localhost): " host
test -n "$host" || host="localhost"
read -p "DB User (default: root): " user
test -n "$user" || user="root"
read -p "DB Pass (default: kiwi-kawaii): " pass
test -n "$pass" || pass="kiwi-kawaii"
read -p "DB Name (default: darakbang.engine): " dbname
test -n "$dbname" || dbname="darakbang.engine"

echo "DATABASE_URL=mysql://${user}:${pass}@${host}/${dbname}" > .env
echo >> .env
