version: '3.7'
services:
  server:
    build: .
    ports:
      - "80:80"
    links:
      - database
    environment:
      DATABASE_URL: mysql://root:kiwi-kawaii@mysql/darakbang.engine
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kiwi-kawaii
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: {}