version: '3.7'
services:
  server:
    build: .
    ports:
      - "80:80"
    links:
      - database
    environment:
      DATABASE_URL: mysql://darakbang:kiwi-kawaii@database/darakbang
      BIND_ADDRESS: 0.0.0.0:80
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: darakbang
      MYSQL_USER: darakbang
      MYSQL_PASSWORD: kiwi-kawaii
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
volumes:
  mysql-data: {}
